### ISSUE TITLE
Improve output when running a workload

### ISSUE THREAD

**Issue by rzvoncek** [thelastpickle/tlp-stress#19]
When running tlp-stress, the Dropwizard's metric reporter prints tens of lines each second. This leads to a very long history in the terminal output, specially for long running command.

It would be nice to have the reporter over-write its previous output instead.

One way of solving this is to use the [cursor up characters](http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html) combined with carriage returns (`'\r'`). The hardest part of this seems to be smuggling printing the cursor up chars to the metric reporter.

**Comment by rustyrazorblade** [comment]
To be honest I only have the reporter printing to the screen as a stop gap.  There are going to be more metrics coming and as you noticed it's not helpful to spam the screen.  I'm thinking long term we might want to include a docker compose configuration file that launches Prometheus, and it's auto hooked together.

**Comment by rustyrazorblade** [comment]
I looked into this a little bit and I think our best option will end up being creating our own reporter like this:

https://metrics.dropwizard.io/3.1.0/apidocs/com/codahale/metrics/ConsoleReporter.html
