### ISSUE TITLE
support machine readable file output

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/tlp-stress#30]
The human readable output is great if you're watching one test, but for doing a run of 50 variations (some crazy test matrix) you'd probably want to put the output somewhere and compare the results.

probably something like   `--csv filename.csv` or `--json filename.json`.  CSV is preferred, it's lighter.  Will see what's available in metrics lib. 

Reporter will be something similar to this: https://github.com/thelastpickle/tlp-stress/blob/master/src/main/kotlin/com/thelastpickle/tlpstress/SingleLineConsoleReporter.kt

\cc @amorton

**Comment by famousj** [comment]
See PR:
https://github.com/thelastpickle/tlp-stress/pull/55
