### ISSUE TITLE
Allow tlp-stress to run on Cassandra clusters with PasswordAuthentication enabled

### ISSUE THREAD

**Issue by arodrime** [thelastpickle/tlp-stress#36]
I face this issue when trying to run tlp-stress on a cluster with authentication enabled:

```
07:58:47.990 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[myDNS/myIP:9042-1, inFlight=0, closed=true] closing connection
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host myDNS/myIP:9042: Host myDNS/myIP:9042 requires authentication, but no authenticator found in Cluster configuration
```

It seems that the tlp-stress tool does not handle authentication yet as I could not find an option to pass or a configuration file to use for this purpose.

**Comment by rustyrazorblade** [comment]
Adding a user and password option to `com.thelastpickle.tlpstress.commands.Run` should be straightforward.  We'd need to add the auth options to the cluster builder:

See line 76 of com.thelastpickle.tlpstress.commands.Run#execute:

```
 val cluster = Cluster.builder().addContactPoint(host).build()
```

Want to take a stab at it? Maybe @adejanovski  or @rzvoncek?

**Comment by rzvoncek** [comment]
I'll take a stab.

**Comment by rzvoncek** [comment]
There's now a PR doing this: https://github.com/thelastpickle/tlp-stress/pull/37
