### ISSUE TITLE
Improve CSV reporting

### ISSUE THREAD

**Issue by muru** [thelastpickle/tlp-stress#85]
#62  changed the directory names to something more readable; but I feel it cost some usability. If the directory names were like `2019-07-31 18:36:19` (`%F %T` with `date` or `strftime(2)`, or `yyyy-MM-dd HH:mm:ss` in Kotlin?), they might perhaps be less readable, but when sorted lexicographically, get arranged properly by time. The current format isn't all the helpful for that case. For comparison, here's the same directories in both formats (`ls` sorts alphabetically by default):

```
$ ls -1
metrics-30May19-13.28.49
metrics-30May19-13.7.56
metrics-30May19-14.3.36
metrics-30May19-17.52.57
metrics-30May19-18.42.3
metrics-31May19-11.36.13
new-2019-05-30.13:07:56
new-2019-05-30.13:28:49
new-2019-05-30.14:03:36
new-2019-05-30.17:52:57
new-2019-05-30.18:42:03
new-2019-05-31.11:36:13
```
The `new-*` directories are perfectly ordered. Would it be possible to customize the directory name pattern, or set it to something sortable?

In case it isn't, here's a shell snippet for renaming them:

```sh
printf "%s\n" metrics-* | while IFS=-. read pre d h m s; 
do
  new=$(date -d "$d $h:$(printf "%02d" $m):$s" +"$pre-%F.%T"); 
  echo mv -a "$pre-$d-$h.$m.$s" "$new"; # remove echo to actually rename
done
```

**Comment by rustyrazorblade** [comment]
After using this for a while I think it would be better if the output got explicitly named instead of assuming a timestamp name.  I've lost track of what files were from what run and I think outputting a single named CSV would be better than a directory as well.

**Comment by rustyrazorblade** [comment]
Pushed this up.  We're now logging to a single text file, the output looks like this:

![image](https://user-images.githubusercontent.com/337872/60630444-09c12000-9daf-11e9-9130-380a24e81369.png)
