### ISSUE TITLE
Missing version and license info

### ISSUE THREAD

**Issue by storbeck** [thelastpickle/tlp-stress#86]
Is it possible to add a version number and a license? We are running into roadblocks using it in our environment since tlp-stress is missing these things. I see an issue #61 you said you were working on version 1.0 release but that was in March.

**Comment by rustyrazorblade** [comment]
I thought I had a license in here, good catch.  I'll have that up today.

Regarding the version, I've been a bit busy and haven't been able to get the 1.0 version released.  I'm not sure how long it'll be, there's a few features that I consider to be pretty important before I'm putting the 1.0 stamp on things.
